# flowguard-api/pytest.ini                                                                                  
[pytest]                                                                                              
pythonpath = . 