[lb]
34.142.204.201 ansible_user=ansible

[backend]
# populated by scripts/update-inventory.sh after terraform apply
# dummy entry for testing nginx config render on a single VM:
127.0.0.1

[flowguard:children]
lb
backend
