---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true
  tags: [nginx_lb]

- name: Deploy nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
    validate: 'nginx -t -c %s'
  notify: Reload Nginx
  tags: [nginx_lb]

- name: Install Certbot and Nginx plugin
  ansible.builtin.apt:
    name:
      - certbot
      - python3-certbot-nginx
    state: present
    update_cache: true
  tags: [nginx_lb]

- name: Enable and start Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  tags: [nginx_lb]

- name: Reload Nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  tags: [nginx_lb]
